### ISSUE TITLE
Downloads "Built on" headers look weird squished to the left

### ISSUE THREAD

**Issue by StephenBrown2** [rockstor/rockstor-website#31]
When I attempt to load https://rockstor.com/dls.html in my browser (Firefox 95.0.1 (64-bit) on Ubuntu 20.04.3), I am greeted by many offset titles where I would presume a logo should be:
![image](https://user-images.githubusercontent.com/1148665/149238579-39bd813e-d6cf-465c-9ee8-e01b0e7d296d.png)

However, I see that that this is specifically done without an image here: https://github.com/rockstor/rockstor-website/blob/master/layouts/dls/list.html#L26-L29

In my mind, if the header was not squished to the left side but rather only left-justified, it would look better than it does now. Why was `col-sm-4` chosen as the width for the "Built on" header? Could it be extended to at least `col-6` for a 50% width?

**Comment by phillxnet** [comment]
@StephenBrown2 OK, do you fancy submitting a pull request as a proof of concept. We can then see if the col-6 suggestion, or whatever comes from experimentation looks better.

The left placement was intentional to seperate it from the the Architecture. But the colouring could just as well do this. We also have this type of left header then center subheader style elsewhere. But I'm game for entertaining refinements.

Try submitting a tested pr and I'll take a look. We definitely need more input on the hugo side that only me anyway as I basically learned Hugo with this project (and a smaller one directly before this). And most theming was heavily influenced from our donor prior website which was an orphan from a prior static site generator.

Personally I like them on the left but they would do better to not be squished which I think is your main suggestion here.

Thanks again and do pop in a tested pr and I'll take a look and gladly merge if it's even standing next to an improvement :).

> Why was `col-sm-4` chosen as the width for the "Built on" header?

I'm afraid I had very limited time to tweak. So as soon as I got something that basically worked I had to move on. Your input on this would be much appreciated so do dive in with a pr if you find the time. But do test first, because as you likely know, stuff can not always be fixed as simply as it first appears.

Cheers. And nice to see you in this repository as well by the way.

**Comment by phillxnet** [comment]
Oh and a quick follow-up.
Yes, no logo is intended or wanted on these entries.

**Comment by StephenBrown2** [comment]
Thanks for the response! Unfortunately I'm in the middle of a house renovation, so I haven't much time to work on a PR, but I can definitely understand the reasoning better, and the recent updates make it look better (though the title case Diy and Rpm are meh :-p ).

I hope to be more involved when I can get my Rockstor box up again after the dust settles (literally).

**Comment by phillxnet** [comment]
Closing as essentially cosmetic and I want to avoid long standing cosmetic related issues in this repository.
Especially since we are still updating our core libs here. We may end up having more options going forward post library updates so we can revisit layout issues post those changes. I'll get to issuing these soon hopefully.
