### ISSUE TITLE
Improve home page header text

### ISSUE THREAD

**Issue by phillxnet** [rockstor/rockstor-website#88]
Currently we have, a thrown together at the time (by me):
**Rockstor now on Pi4 Ten64 & More**

Where-as, given the increasing number of aarch64 SBC, some of which our Ten64 ARM64EFI installers will work on, via the [Embedded Boot](https://github.com/ARM-software/ebbr) or [Server boot](https://github.com/ARM-software/sbsa-acs) standard, it is proposed that we modify this key header to emphasise the ARM64EFI compatibility and not have this over-rule our X86_64 stalwart compatibility.

I'm thinking here of half-brained reviews indicating our CentOS x86_64 only nature from many years ago! - while showing a picture of the Pi4 (in famous case) in a presumably automated screen home page grab.

So we are after something to highlighting our cross arch capability i.e. 'AMD64/ARM64EFI' in line with @Hooverdan96's work to formalise our arch referenced in for example https://github.com/rockstor/rockon-registry/pull/323 , and given the **Ten64** platform folks (via @mcbridematt) have supported the project via hardware donation and code contribution/review it would be nice to maintain the Ten64 highlight here: especially given we have installers custom made for them (again thanks to @mcbridematt) and we feature in their docs:
https://ten64doc.traverse.com.au/applications/doesitrun/#storage-and-nas
https://ten64doc.traverse.com.au/applications/rockstor/

So all in what this looks to boil down to is more explict mention of both architectures while maintaining single line succinctness, and ideally also have for example a 'Uses openSUSE' element in there. Doable with a reduction in conjunction likely.

Many folks will see only pics and heading - and if nothing grabs their eye or they miss-read they may think we are a custom OS with little backing yet appreciate the difficulty of rolling ones own - yet this appreciation is in part a defining characteristic of the DIY NAS audience. So lets update this header a tad to not throw the baby out with the bath-water :).

**Comment by Hooverdan96** [comment]
How about a tagline like:

"Rockstor, a multi-architecture (AMD64 & ARM64EFI) NAS appliance, using BTRFS and powered by OpenSuSE"

I know, not really related, but you might want to fix this error in Rockstor spelling immediately here:

https://github.com/rockstor/rockstor-website/blob/7d3a3f8451d1541429387d56b4f3ce86e4da5bb3/content/solutions/customizable-btrfs-nas-storage-platform.md?plain=1#L49

**Comment by Hooverdan96** [comment]
Do we need the DIY in there, since that's also explained in the other sections below?
Rockstor - a multi-architecture NAS built on openSUSE

and in this section:
![image](https://github.com/rockstor/rockstor-website/assets/35113775/8c75f669-ca31-4f93-9a4f-2d329f7c629e)

add the actual architectures to that:

"Rockstor is a Linux and BTRFS powered storage operating system with advanced NAS and Cloud Storage features, supporting multiple architectures like AMD64/ARM64EFI/Ten64 and more."

**Comment by Hooverdan96** [comment]
yep, like this?

"Rockstor - an Open Source multi-architecture NAS built on OpenSUSE"

of course, we could consider dropping Rockstor in the beginning, since the Website title already shows it with the Logo/Name combo ... then it would become

"An Open Source multi-architecture NAS built on OpenSUSE"
